<?xml version = "1.0" ?>
<robot xmlns:xacro = "http://www.ros.org/wiki/xacro">

    <xacro:property name = "lidar_radius" value = "0.05" />
    <xacro:property name = "lidar_length" value = "0.06" />

    <link name = "lidar_link">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}" />
            </geometry>
            <origin xyz = "0.0 0.0 0.0" rpy = "0.0 0.0 0.0" />
            <material name = "green" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </collision>
        <xacro:cylinder_inertial m = "0.5" r = "${lidar_radius}" h = "${lidar_length}" 
                                 xyz = "0.0 0.0 0.0" rpy = "0.0 0.0 0.0" />
    </link>

    <joint name="lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_link"/>
        <origin xyz = "${(base_length) / 2.0 + lidar_radius} 0 0" rpy = "0 0 0" />
        <axis xyz="0.0 0.0 0.0"/>
    </joint>

    <gazebo reference = "lidar_link">
        <material>Gazebo/Green</material>

        <sensor name = "laser" type = "ray">

            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>30</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <!-- <resolution>1</resolution> -->
                        <min_angle>-1.57</min_angle>
                        <max_angle>1.57</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.1</min>
                    <max>12</max>
                    <!-- <resolution>0.01</resolution> -->
                </range>
            </ray>
            <plugin name = "laser_controller" filename = "libgazebo_ros_ray_sensor.so">
                <ros>
                    <argument>-/out:=scan</argument>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>lidar_link</frame_name>
            </plugin>
        </sensor>

    </gazebo>

</robot>